# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'collegereg.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
import sys
import collegelog
import re
check = True


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(729, 549)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.srwidget = QtWidgets.QWidget(Form)
        self.srwidget.setGeometry(QtCore.QRect(20, 60, 661, 421))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.srwidget.setFont(font)
        self.srwidget.setStyleSheet("QPushButton#crback{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#crback:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton#crback:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#pushButton_CRegister{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_CRegister:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton#pushButton_CRegister:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.srwidget.setObjectName("srwidget")
        self.crlabel = QtWidgets.QLabel(self.srwidget)
        self.crlabel.setGeometry(QtCore.QRect(229, 9, 421, 391))
        self.crlabel.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px")
        self.crlabel.setText("")
        self.crlabel.setObjectName("crlabel")
        self.crlabel_2 = QtWidgets.QLabel(self.srwidget)
        self.crlabel_2.setGeometry(QtCore.QRect(40, 25, 201, 351))
        self.crlabel_2.setStyleSheet("border-top-left-radius:50px;\n"
"background-color:rgba(0,0,0,80);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.crlabel_2.setText("")
        self.crlabel_2.setObjectName("crlabel_2")
        self.crlabel_3 = QtWidgets.QLabel(self.srwidget)
        self.crlabel_3.setGeometry(QtCore.QRect(250, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.crlabel_3.setFont(font)
        self.crlabel_3.setStyleSheet("color:rgba(0,0,0,200);")
        self.crlabel_3.setObjectName("crlabel_3")
        self.lineEdit_Cname = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_Cname.setGeometry(QtCore.QRect(250, 60, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Cname.setFont(font)
        self.lineEdit_Cname.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_Cname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_Cname.setObjectName("lineEdit_Cname")
        self.crlabel_5 = QtWidgets.QLabel(self.srwidget)
        self.crlabel_5.setGeometry(QtCore.QRect(60, 50, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.crlabel_5.setFont(font)
        self.crlabel_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.crlabel_5.setObjectName("crlabel_5")
        self.crlabel_6 = QtWidgets.QLabel(self.srwidget)
        self.crlabel_6.setGeometry(QtCore.QRect(60, 150, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.crlabel_6.setFont(font)
        self.crlabel_6.setStyleSheet("color:rgba(255,255,255,220);")
        self.crlabel_6.setObjectName("crlabel_6")
        self.pushButton_CRegister = QtWidgets.QPushButton(self.srwidget)
        self.pushButton_CRegister.setGeometry(QtCore.QRect(340, 330, 191, 40))
        self.pushButton_CRegister.clicked.connect(self.insertdata)
        
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_CRegister.setFont(font)
        self.pushButton_CRegister.setObjectName("pushButton_CRegister")
        self.crlabel_7 = QtWidgets.QLabel(self.srwidget)
        self.crlabel_7.setGeometry(QtCore.QRect(80, 190, 151, 181))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        font.setPointSize(120)
        font.setBold(False)
        font.setWeight(50)
        self.crlabel_7.setFont(font)
        self.crlabel_7.setObjectName("crlabel_7")
        self.lineEdit_Ccontact = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_Ccontact.setGeometry(QtCore.QRect(250, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Ccontact.setFont(font)
        self.lineEdit_Ccontact.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Ccontact.setObjectName("lineEdit_Ccontact")
        self.lineEdit_CPasswd = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_CPasswd.setGeometry(QtCore.QRect(450, 60, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_CPasswd.setFont(font)
        self.lineEdit_CPasswd.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_CPasswd.setObjectName("lineEdit_CPasswd")
        self.lineEdit_Caddress = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_Caddress.setGeometry(QtCore.QRect(250, 120, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Caddress.setFont(font)
        self.lineEdit_Caddress.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Caddress.setObjectName("lineEdit_Caddress")
        self.lineEdit_CEmail = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_CEmail.setGeometry(QtCore.QRect(450, 180, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_CEmail.setFont(font)
        self.lineEdit_CEmail.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_CEmail.setObjectName("lineEdit_CEmail")
        self.crback = QtWidgets.QPushButton(self.srwidget)
        self.crback.setGeometry(QtCore.QRect(554, 20, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Wingdings 3")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.crback.setFont(font)
        self.crback.setStyleSheet("")
        self.crback.setObjectName("crback")
        self.lineEdit_Cwebsite = QtWidgets.QLineEdit(self.srwidget)
        self.lineEdit_Cwebsite.setGeometry(QtCore.QRect(450, 120, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Cwebsite.setFont(font)
        self.lineEdit_Cwebsite.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Cwebsite.setObjectName("lineEdit_Cwebsite")
        self.crback.clicked.connect(self.passage7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.crlabel_3.setText(_translate("Form", "Registration Form"))
        self.lineEdit_Cname.setPlaceholderText(_translate("Form", "College Name"))
        self.crlabel_5.setText(_translate("Form", "Entrée-in"))
        self.crlabel_6.setText(_translate("Form", "College"))
        self.pushButton_CRegister.setText(_translate("Form", "Register"))
        self.crlabel_7.setText(_translate("Form", "¨"))
        self.lineEdit_Ccontact.setPlaceholderText(_translate("Form", "Contact No."))
        self.lineEdit_CPasswd.setPlaceholderText(_translate("Form", "Password"))
        self.lineEdit_Caddress.setPlaceholderText(_translate("Form", "Address"))
        self.lineEdit_CEmail.setPlaceholderText(_translate("Form", "Email-ID"))
        self.crback.setText(_translate("Form", "8"))
        self.lineEdit_Cwebsite.setPlaceholderText(_translate("Form", "Website"))

        global check
        check = True
        if(check):
                global x
                x = Form
                check = False

    def collegelog(self,x):                            
        self.window3 = QtWidgets.QMainWindow()
        self.ui = collegelog.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()
        x.close()

    def passage7(self):
        self.collegelog(x)

    def insertdata(self):
        College_Name = self.lineEdit_Cname.text()
        College_Passwd = self.lineEdit_CPasswd.text()
        Address = self.lineEdit_Caddress.text()
        Website = self.lineEdit_Cwebsite.text()
        Contact_no = self.lineEdit_Ccontact.text()
        Email_ID = self.lineEdit_CEmail.text()
        if College_Passwd== "":
            self.lineEdit_CPasswd.setText("Field Cannot Be Empty")
            return
        if College_Name== "":
            self.lineEdit_Cname.setText("Field Cannot Be Empty")
            return
        if Address== "":
            self.lineEdit_Caddress.setText("Field Cannot Be Empty")
            return
        if Website== "":
            self.lineEdit_Cwebsite.setText("Field Cannot Be Empty")
            return
        if Contact_no== "":
            self.lineEdit_Ccontact.setText("Field Cannot Be Empty")
            return
        if Email_ID== "":
            self.lineEdit_CEmail.setText("Field Cannot Be Empty")
            return
        try:
            int(Contact_no,16)
            if len(Contact_no)!=10:
                self.lineEdit_Ccontact.setText("Invalid Contact No.")
            else:
                regex = '^(\w|\.|\_|\-)+[@](\w|\_|\-|\.)+[.]\w{2,3}$'
                if(re.search(regex,str(Email_ID))):
                    try:
                        connection = sqlite3.connect("Project.db")
                        connection.execute("INSERT INTO College_Registration (College_Name, College_Passwd, Address, Website, Contact_no, Email_ID)VALUES(?, ?, ?, ?, ?, ?)",(College_Name, College_Passwd, Address, Website, Contact_no, Email_ID))
                        connection.commit()
                        connection.close()
                        self.passage7()
                    except:
                        self.lineEdit_Cname.setText("College Name Already Exists")
                else:
                    self.lineEdit_CEmail.setText("Invalid Email-ID")
        except:
            self.lineEdit_Ccontact.setText("Invalid Contact No.")
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
