# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myinfostudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import sys

from PyQt5.QtCore import QDate
from PyQt5.QtPrintSupport import QPrinter, QPrintDialog, QPrintPreviewDialog

import student1
import sqlite3

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1111, 754)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.a1widget = QtWidgets.QWidget(Form)
        self.a1widget.setGeometry(QtCore.QRect(20, 20, 1091, 771))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.a1widget.setFont(font)
        self.a1widget.setStyleSheet("")
        self.a1widget.setObjectName("a1widget")
        self.a1label = QtWidgets.QLabel(self.a1widget)
        self.a1label.setGeometry(QtCore.QRect(10, 40, 1061, 691))
        self.a1label.setStyleSheet("background-color:rgba(255,255,255,255);\n"
"border-bottom-right-radius:50px")
        self.a1label.setText("")
        self.a1label.setObjectName("a1label")
        self.a1label_2 = QtWidgets.QLabel(self.a1widget)
        self.a1label_2.setGeometry(QtCore.QRect(0, 20, 211, 71))
        self.a1label_2.setStyleSheet("border-top-left-radius:50px;\n"
"background-color:rgba(0,0,0,80);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.a1label_2.setText("")
        self.a1label_2.setObjectName("a1label_2")
        self.a1label_5 = QtWidgets.QLabel(self.a1widget)
        self.a1label_5.setGeometry(QtCore.QRect(20, 40, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_5.setFont(font)
        self.a1label_5.setStyleSheet("color:rgba(255,255,255,220);")
        self.a1label_5.setObjectName("a1label_5")
        self.a1label_6 = QtWidgets.QLabel(self.a1widget)
        self.a1label_6.setGeometry(QtCore.QRect(450, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_6.setFont(font)
        self.a1label_6.setStyleSheet("color:rgba(0,0,0,200);")
        self.a1label_6.setObjectName("a1label_6")
        self.astudentinfo_Submit = QtWidgets.QPushButton(self.a1widget)
        self.astudentinfo_Submit.setGeometry(QtCore.QRect(400, 630, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.astudentinfo_Submit.setFont(font)
        self.astudentinfo_Submit.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.astudentinfo_Submit.setObjectName("astudentinfo_Submit")

        # self.Print_Preview = QtWidgets.QPushButton(self.a1widget)
        # self.Print_Preview.setGeometry(QtCore.QRect(550, 630, 191, 31))
        # font = QtGui.QFont()
        # font.setPointSize(11)
        # font.setBold(True)
        # font.setWeight(75)
        # self.Print_Preview.setFont(font)
        # self.Print_Preview.setStyleSheet("QPushButton{\n"
        #                                        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
        #                                        "    color:rgba(255,255,255,210);\n"
        #                                        "    border-radius:5px;\n"
        #                                        "}\n"
        #                                        "QPushButton:pressed{\n"
        #                                        "    padding-left:5px;\n"
        #                                        "    padding-top:5px;\n"
        #                                        "    background-color:rgba(150,123,111,255);\n"
        #                                        "}\n"
        #                                        "QPushButton:hover{\n"
        #                                        "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
        #                                        "}")
        # self.Print_Preview.setObjectName("Print Preview")

        self.a1home = QtWidgets.QPushButton(self.a1widget)
        self.a1home.setGeometry(QtCore.QRect(990, 50, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.a1home.setFont(font)
        self.a1home.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255,255,255,210);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150,123,111,255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}")
        self.a1home.setObjectName("a1home")
        self.lineEdit_Fname = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Fname.setGeometry(QtCore.QRect(40, 190, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Fname.setFont(font)
        self.lineEdit_Fname.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_Fname.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Fname.setObjectName("lineEdit_Fname")
        self.lineEdit_LName = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_LName.setGeometry(QtCore.QRect(250, 190, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_LName.setFont(font)
        self.lineEdit_LName.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_LName.setObjectName("lineEdit_LName")
        self.a1label_7 = QtWidgets.QLabel(self.a1widget)
        self.a1label_7.setGeometry(QtCore.QRect(40, 130, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_7.setFont(font)
        self.a1label_7.setStyleSheet("color:rgba(0,0,0,200);")
        self.a1label_7.setObjectName("a1label_7")
        self.lineEdit_Father = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Father.setGeometry(QtCore.QRect(460, 190, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Father.setFont(font)
        self.lineEdit_Father.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Father.setObjectName("lineEdit_Father")
        self.lineEdit_Mother = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Mother.setGeometry(QtCore.QRect(670, 190, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Mother.setFont(font)
        self.lineEdit_Mother.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Mother.setObjectName("lineEdit_Mother")
        self.lineEdit_Mobile = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Mobile.setGeometry(QtCore.QRect(460, 230, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Mobile.setFont(font)
        self.lineEdit_Mobile.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Mobile.setObjectName("lineEdit_Mobile")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Email.setGeometry(QtCore.QRect(670, 230, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Email.setFont(font)
        self.lineEdit_Email.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Email.setText("")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.lineEdit_Aadhar = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Aadhar.setGeometry(QtCore.QRect(40, 230, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Aadhar.setFont(font)
        self.lineEdit_Aadhar.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Aadhar.setObjectName("lineEdit_Aadhar")
        self.lineEdit_District = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_District.setGeometry(QtCore.QRect(870, 230, 190, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_District.setFont(font)
        self.lineEdit_District.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_District.setText("")
        self.lineEdit_District.setObjectName("lineEdit_District")
        self.lineEdit_Address = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Address.setGeometry(QtCore.QRect(40, 270, 611, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Address.setFont(font)
        self.lineEdit_Address.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Address.setObjectName("lineEdit_Address")
        self.a1label_8 = QtWidgets.QLabel(self.a1widget)
        self.a1label_8.setGeometry(QtCore.QRect(40, 310, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_8.setFont(font)
        self.a1label_8.setStyleSheet("color:rgba(0,0,0,200);")
        self.a1label_8.setObjectName("a1label_8")
        self.lineEdit_10YOP = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10YOP.setGeometry(QtCore.QRect(250, 350, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10YOP.setFont(font)
        self.lineEdit_10YOP.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10YOP.setObjectName("lineEdit_10YOP")
        self.lineEdit_10Board = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10Board.setGeometry(QtCore.QRect(40, 350, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10Board.setFont(font)
        self.lineEdit_10Board.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10Board.setObjectName("lineEdit_10Board")
        self.lineEdit_10MScored = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10MScored.setGeometry(QtCore.QRect(460, 350, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10MScored.setFont(font)
        self.lineEdit_10MScored.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10MScored.setObjectName("lineEdit_10MScored")
        self.lineEdit_10Seat = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10Seat.setGeometry(QtCore.QRect(250, 310, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10Seat.setFont(font)
        self.lineEdit_10Seat.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10Seat.setText("")
        self.lineEdit_10Seat.setObjectName("lineEdit_10Seat")
        self.lineEdit_10Per = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10Per.setGeometry(QtCore.QRect(870, 350, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10Per.setFont(font)
        self.lineEdit_10Per.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10Per.setObjectName("lineEdit_10Per")
        self.lineEdit_10Total = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_10Total.setGeometry(QtCore.QRect(670, 350, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_10Total.setFont(font)
        self.lineEdit_10Total.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_10Total.setObjectName("lineEdit_10Total")
        self.a1label_9 = QtWidgets.QLabel(self.a1widget)
        self.a1label_9.setGeometry(QtCore.QRect(40, 400, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_9.setFont(font)
        self.a1label_9.setStyleSheet("color:rgba(0,0,0,200);")
        self.a1label_9.setObjectName("a1label_9")
        self.lineEdit_12Board = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_12Board.setGeometry(QtCore.QRect(40, 440, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12Board.setFont(font)
        self.lineEdit_12Board.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12Board.setObjectName("lineEdit_12Board")
        self.lineEdit_12YOP = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_12YOP.setGeometry(QtCore.QRect(250, 440, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12YOP.setFont(font)
        self.lineEdit_12YOP.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12YOP.setObjectName("lineEdit_12YOP")
        self.lineEdit_MScored12 = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_MScored12.setGeometry(QtCore.QRect(460, 440, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_MScored12.setFont(font)
        self.lineEdit_MScored12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_MScored12.setObjectName("lineEdit_MScored12")
        self.lineEdit_12Total = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_12Total.setGeometry(QtCore.QRect(670, 440, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12Total.setFont(font)
        self.lineEdit_12Total.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12Total.setObjectName("lineEdit_12Total")
        self.lineEdit_12Per = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_12Per.setGeometry(QtCore.QRect(870, 440, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12Per.setFont(font)
        self.lineEdit_12Per.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12Per.setText("")
        self.lineEdit_12Per.setObjectName("lineEdit_12Per")
        self.lineEdit_12Seat = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_12Seat.setGeometry(QtCore.QRect(250, 400, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_12Seat.setFont(font)
        self.lineEdit_12Seat.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_12Seat.setObjectName("lineEdit_12Seat")
        self.a1label_11 = QtWidgets.QLabel(self.a1widget)
        self.a1label_11.setGeometry(QtCore.QRect(40, 530, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.a1label_11.setFont(font)
        self.a1label_11.setStyleSheet("color:rgba(0,0,0,200);")
        self.a1label_11.setObjectName("a1label_11")
        self.lineEdit_Physics = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Physics.setGeometry(QtCore.QRect(40, 570, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Physics.setFont(font)
        self.lineEdit_Physics.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Physics.setObjectName("lineEdit_Physics")
        self.lineEdit_Chemistry = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Chemistry.setGeometry(QtCore.QRect(250, 570, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Chemistry.setFont(font)
        self.lineEdit_Chemistry.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Chemistry.setObjectName("lineEdit_Chemistry")
        self.lineEdit_Mathematics = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Mathematics.setGeometry(QtCore.QRect(460, 570, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Mathematics.setFont(font)
        self.lineEdit_Mathematics.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Mathematics.setObjectName("lineEdit_Mathematics")
        self.lineEdit_Total = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Total.setGeometry(QtCore.QRect(670, 570, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Total.setFont(font)
        self.lineEdit_Total.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Total.setObjectName("lineEdit_Total")
        self.lineEdit_Mathematics12 = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Mathematics12.setGeometry(QtCore.QRect(460, 480, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Mathematics12.setFont(font)
        self.lineEdit_Mathematics12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Mathematics12.setObjectName("lineEdit_Mathematics12")
        self.lineEdit_Chemistry12 = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Chemistry12.setGeometry(QtCore.QRect(250, 480, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Chemistry12.setFont(font)
        self.lineEdit_Chemistry12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Chemistry12.setObjectName("lineEdit_Chemistry12")
        self.lineEdit_Physics12 = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Physics12.setGeometry(QtCore.QRect(40, 480, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Physics12.setFont(font)
        self.lineEdit_Physics12.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Physics12.setObjectName("lineEdit_Physics12")
        self.lineEdit_Bifocal = QtWidgets.QLineEdit(self.a1widget)
        self.lineEdit_Bifocal.setGeometry(QtCore.QRect(670, 480, 190, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_Bifocal.setFont(font)
        self.lineEdit_Bifocal.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,240);\n"
"padding-bottom:7px;")
        self.lineEdit_Bifocal.setObjectName("lineEdit_Bifocal")
        self.dateEdit_DOB = QtWidgets.QDateEdit(self.a1widget)
        self.dateEdit_DOB.setGeometry(QtCore.QRect(250, 220, 191, 31))
        self.dateEdit_DOB.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.dateEdit_DOB.setObjectName("dateEdit_DOB")
        self.comboBox_Gender = QtWidgets.QComboBox(self.a1widget)
        self.comboBox_Gender.setGeometry(QtCore.QRect(870, 180, 191, 31))
        self.comboBox_Gender.setMouseTracking(False)
        self.comboBox_Gender.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.comboBox_Gender.setObjectName("comboBox_Gender")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_Gender.addItem("")
        self.comboBox_State = QtWidgets.QComboBox(self.a1widget)
        self.comboBox_State.setGeometry(QtCore.QRect(670, 260, 191, 31))
        self.comboBox_State.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));")
        self.comboBox_State.setObjectName("comboBox_State")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")
        self.comboBox_State.addItem("")

        self.messageLabel1 = QtWidgets.QLabel(Form)
        self.messageLabel1.setGeometry(QtCore.QRect(450, 690, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.messageLabel1.setFont(font)
        self.messageLabel1.setStyleSheet("color: #6B6B6B;")
        self.messageLabel1.setText("")
        self.messageLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.messageLabel1.setWordWrap(False)
        self.messageLabel1.setObjectName("messageLabel")

        self.astudentinfo_Submit.clicked.connect(self.passage1)
        # self.Print_Preview.setEnabled(False)
        # self.Print_Preview.clicked.connect(self.passage2)
        self.a1home.clicked.connect(self.passage)
        self.retranslateUi(Form)
        try:
                connection = sqlite3.connect("Project.db")
                cursor = connection.cursor()
                S_user = cursor.execute(f"SELECT * FROM Current_login WHERE No = '{1}'")
                record = S_user.fetchone()
                self.user = record[0]

                data = cursor.execute(f"SELECT * FROM Student_Registration WHERE Username = '{self.user}'")
                records = data.fetchone()
                f_name = records[2]
                l_name = records[3]
                father = records[4]
                mother = records[5]
                gender = records[6]
                date1 = records[7]
                y = int(date1[0:4])
                m = int(date1[5:7])
                d = int(date1[8:10])
                aadhar1 = records[8]
                mob = records[9]
                email = records[10]
                addre = records[11]
                district = records[12]
                state = records[13]

                self.lineEdit_Fname.setText(f_name)
                self.lineEdit_LName.setText(l_name)
                self.lineEdit_Father.setText(father)
                self.lineEdit_Mother.setText(mother)
                self.lineEdit_Aadhar.setText(f"{aadhar1}")
                self.lineEdit_Mobile.setText(f"{mob}")
                self.lineEdit_Email.setText(email)
                self.lineEdit_Address.setText(addre)
                self.lineEdit_District.setText(district)
                self.comboBox_State.setCurrentText(state)
                self.comboBox_Gender.setCurrentText(gender)
                dat = QDate(y,m,d)
                self.dateEdit_DOB.setDate(dat)
                connection.close()
        except Exception as e:
                print(e)
                print("Upload Interepted")
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.a1label_5.setText(_translate("Form", "Student"))
        self.a1label_6.setText(_translate("Form", "My Information"))
        self.astudentinfo_Submit.setText(_translate("Form", "Submit"))
        # self.Print_Preview.setText(_translate("Form", "Print Preview"))
        self.a1home.setText(_translate("Form", "Home"))
        self.lineEdit_Fname.setPlaceholderText(_translate("Form", "First Name"))
        self.lineEdit_LName.setPlaceholderText(_translate("Form", " Last Name"))
        self.a1label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400;\">Previous Information</span></p></body></html>"))
        self.lineEdit_Father.setPlaceholderText(_translate("Form", "Father Name"))
        self.lineEdit_Mother.setPlaceholderText(_translate("Form", "Mother Name"))
        self.lineEdit_Mobile.setPlaceholderText(_translate("Form", "Mobile no."))
        self.lineEdit_Email.setPlaceholderText(_translate("Form", "Email ID"))
        self.lineEdit_Aadhar.setPlaceholderText(_translate("Form", "Aadhar no."))
        self.lineEdit_District.setPlaceholderText(_translate("Form", "District"))
        self.lineEdit_Address.setPlaceholderText(_translate("Form", "Address"))
        self.a1label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400;\">10th Information</span></p></body></html>"))
        self.lineEdit_10YOP.setPlaceholderText(_translate("Form", " Year of Passing"))
        self.lineEdit_10Board.setPlaceholderText(_translate("Form", "Board"))
        self.lineEdit_10MScored.setPlaceholderText(_translate("Form", "Marks Scored"))
        self.lineEdit_10Seat.setPlaceholderText(_translate("Form", "Seat no."))
        self.lineEdit_10Per.setPlaceholderText(_translate("Form", "Percentage"))
        self.lineEdit_10Total.setPlaceholderText(_translate("Form", "Total Marks"))
        self.a1label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400;\">12th Information</span></p></body></html>"))
        self.lineEdit_12Board.setPlaceholderText(_translate("Form", "Board"))
        self.lineEdit_12YOP.setPlaceholderText(_translate("Form", "Year of Passing"))
        self.lineEdit_MScored12.setPlaceholderText(_translate("Form", "Marks Scored"))
        self.lineEdit_12Total.setPlaceholderText(_translate("Form", "Total Marks"))
        self.lineEdit_12Per.setPlaceholderText(_translate("Form", "Percentage"))
        self.lineEdit_12Seat.setPlaceholderText(_translate("Form", "Seat no."))
        self.a1label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:400;\">CET Information :</span></p></body></html>"))
        self.lineEdit_Physics.setPlaceholderText(_translate("Form", "Physics Percentile"))
        self.lineEdit_Chemistry.setPlaceholderText(_translate("Form", "Chemistry Percentile"))
        self.lineEdit_Mathematics.setPlaceholderText(_translate("Form", "Mathematics Percentile"))
        self.lineEdit_Total.setPlaceholderText(_translate("Form", "Total Percentile"))
        self.lineEdit_Mathematics12.setPlaceholderText(_translate("Form", "Mathematics Marks"))
        self.lineEdit_Chemistry12.setPlaceholderText(_translate("Form", "Chemistry Marks"))
        self.lineEdit_Physics12.setPlaceholderText(_translate("Form", " Physics Marks"))
        self.lineEdit_Bifocal.setPlaceholderText(_translate("Form", "Bi-focal Marks"))
        self.comboBox_Gender.setItemText(0, _translate("Form", "Gender"))
        self.comboBox_Gender.setItemText(1, _translate("Form", "Male"))
        self.comboBox_Gender.setItemText(2, _translate("Form", "Female"))
        self.comboBox_Gender.setItemText(3, _translate("Form", "Others"))
        self.comboBox_State.setItemText(0, _translate("Form", "State"))
        self.comboBox_State.setItemText(1, _translate("Form", "Maharashtra"))
        self.comboBox_State.setItemText(2, _translate("Form", "Karnataka"))
        self.comboBox_State.setItemText(3, _translate("Form", "Gujarat"))
        self.comboBox_State.setItemText(4, _translate("Form", "Rajasthan"))
        self.comboBox_State.setItemText(5, _translate("Form", "Tamil Nadu"))
        global check
        check = True
        if (check):
                global x
                x = Form
                check = False

    def passage(self):
            self.studenthome(x)

    def studenthome(self,x):
        self.window3 = QtWidgets.QMainWindow()
        self.ui = student1.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()
        x.close()

    # def passage2(self):
    #         printer=QPrinter(QPrinter.HighResolution)
    #         dialog=QPrintDialog(printer,self)
    #
    #         if dialog.exec_() == QPrintDialog.accepted():
    #                 self.a1widget.print_(printer)
    #         # printer=QPrinter(QPrinter.A4)
    #         # previewdialog=QPrintPreviewDialog(printer, self)
    #         # previewdialog.paintRequested.connect(self.print_preview)
    #         # previewdialog.exec_()
    #
    # def print_preview(self, printer):
    #         self.a1widget.print_(printer)

    def passage1(self):
        self.submit_Check(x)

    def submit_Check(self, x):
            First_Name = self.lineEdit_Fname.text()
            Last_Name = self.lineEdit_LName.text()
            Father_Name = self.lineEdit_Father.text()
            Mother_Name = self.lineEdit_Mother.text()
            Gender = self.comboBox_Gender.currentText()
            dob1 = self.dateEdit_DOB.date()
            dob = dob1.toPyDate()
            Aadhar_no = self.lineEdit_Aadhar.text()
            Mobile_no = self.lineEdit_Mobile.text()
            Email_ID = self.lineEdit_Email.text()
            Address = self.lineEdit_Address.text()
            District = self.lineEdit_District.text()
            State = self.comboBox_State.currentText()

            Seat10=self.lineEdit_10Seat.text()
            Board10=self.lineEdit_10Board.text()
            Yop10=self.lineEdit_10YOP.text()
            Am10=self.lineEdit_10Total.text()
            Max10=self.lineEdit_10MScored.text()
            Per10=self.lineEdit_10Per.text()

            Seat12=self.lineEdit_12Seat.text()
            Board12=self.lineEdit_12Board.text()
            Yop12=self.lineEdit_12YOP.text()
            Am12=self.lineEdit_12Total.text()
            Max12=self.lineEdit_MScored12.text()
            Per12=self.lineEdit_12Per.text()
            Phy12=self.lineEdit_Physics12.text()
            Math12=self.lineEdit_Mathematics12.text()
            Chem12=self.lineEdit_Chemistry12.text()
            Bifocal=self.lineEdit_Bifocal.text()

            Phycet=self.lineEdit_Physics.text()
            Mathcet=self.lineEdit_Mathematics.text()
            Chemcet=self.lineEdit_Chemistry.text()
            Totalcet=self.lineEdit_Total.text()


            if First_Name == "":
                    self.lineEdit_Fname.setText("Field Cannot Be Empty")
                    return
            if Last_Name == "":
                    self.lineEdit_LName.setText("Field Cannot Be Empty")
                    return
            if Father_Name == "":
                    self.lineEdit_Father.setText("Field Cannot Be Empty")
                    return
            if Mother_Name == "":
                    self.lineEdit_Mother.setText("Field Cannot Be Empty")
                    return
            if Aadhar_no == "":
                    self.lineEdit_Aadhar.setText("Field Cannot Be Empty")
                    return
            if Mobile_no == "":
                    self.lineEdit_Mobile.setText("Field Cannot Be Empty")
                    return
            if Email_ID == "":
                    self.lineEdit_Email.setText("Field Cannot Be Empty")
                    return
            if Address == "":
                    self.lineEdit_Address.setText("Field Cannot Be Empty")
                    return
            if District == "":
                    self.lineEdit_District.setText("Field Cannot Be Empty")
                    return
            if Seat10 == "":
                    self.lineEdit_10Seat.setText("Field Cannot be Empty")
                    return
            if Board10 == "":
                    self.lineEdit_10Board.setText("Field Cannot be Empty")
                    return
            if Yop10 == "":
                    self.lineEdit_10YOP.setText("Field Cannot be Empty")
                    return
            if Am10 == "":
                    self.lineEdit_10MScored.setText("Field Cannot be Empty")
                    return
            if Max10 == "":
                    self.lineEdit_10Total.setText("Field Cannot be Empty")
                    return
            if Per10 == "":
                    self.lineEdit_10Per.setText("Field Cannot be Empty")
                    return

            if Seat12 == "":
                    self.lineEdit_12Seat.setText("Field Cannot be Empty")
                    return
            if Board12 == "":
                    self.lineEdit_12Board.setText("Field Cannot be Empty")
                    return
            if Yop12 == "":
                    self.lineEdit_12YOP.setText("Field Cannot be Empty")
                    return
            if Am12 == "":
                    self.lineEdit_MScored12.setText("Field Cannot be Empty")
                    return
            if Max12 == "":
                    self.lineEdit_12Total.setText("Field Cannot be Empty")
                    return
            if Per12 == "":
                    self.lineEdit_12Per.setText("Field Cannot be Empty")
                    return

            if Phy12 == "":
                    self.lineEdit_Physics12.setText("Field Cannot be Empty")
                    return
            if Math12 == "":
                    self.lineEdit_Mathematics12.setText("Field Cannot be Empty")
                    return
            if Chem12 == "":
                    self.lineEdit_Chemistry12.setText("Field Cannot be Empty")
                    return
            if Bifocal == "":
                    self.lineEdit_Bifocal.setText("Field Cannot be Empty")
                    return
            if Phycet == "":
                    self.lineEdit_Physics.setText("Field Cannot be Empty")
                    return
            if Mathcet == "":
                    self.lineEdit_Mathematics.setText("Field Cannot be Empty")
                    return
            if Chemcet == "":
                    self.lineEdit_Chemistry.setText("Field Cannot be Empty")
                    return
            if Totalcet == "":
                    self.lineEdit_Total.setText("Field Cannot be Empty")
                    return

            try:
                    int(Mobile_no, 10)
                    if len(Mobile_no) != 10:
                            self.lineEdit_Mobile.setText("Invalid Mobile No.")
                    else:
                            try:
                                    int(Aadhar_no, 10)
                                    if len(Aadhar_no) != 12:
                                            self.lineEdit_Aadhar.setText("Invalid Aadhar No.")
                                    else:
                                            regex = '^(\w|\.|\_|\-)+[@](\w|\_|\-|\.)+[.]\w{2,3}$'
                                            if (re.search(regex, str(Email_ID))):
                                                    try:
                                                            connection = sqlite3.connect("Project.db")
                                                            connection.execute(f"Update Student_Registration set First_Name='{First_Name}',Last_Name='{Last_Name}',Father_Name='{Father_Name}',Mother_Name='{Mother_Name}',Gender='{Gender}',DOB='{dob}',Aadhar_no='{Aadhar_no}',Mobile_no='{Mobile_no}',Email_ID='{Email_ID}',Address='{Address}',District='{District}',State='{State}' where Username ='{self.user}'")
                                                            connection.commit()
                                                            connection.close()
                                                    except Exception as e:
                                                            print(e)
                                                            print("registration updation error")
                                                            self.messageLabel1.setText("Updation Failed Try Again")

                                                    try:
                                                            connection = sqlite3.connect("Project.db")
                                                            connection.execute(
                                                                   # f"Insert into Student_Information S_Name='{First_Name}',DOB='{dob}',Mobile_no='{Mobile_no}',Email_ID='{Email_ID}',Physics='{Phycet}',Chemistry='{Chemcet}',Mathematics='{Mathcet}',Total='{Totalcet}'")
                                                                     f"Insert into Student_Information (S_Name,Email_ID,Mobile,DOB,Physics,Chemistry,Mathematics,Total)Values(?, ?, ?, ?, ?, ?, ?, ?)", (First_Name, Email_ID, Mobile_no, dob, Phycet, Chemcet,Mathcet, Totalcet))

                                                            connection.commit()
                                                            connection.close()
                                                    except Exception as e:
                                                            print(e)
                                                            print("Inserting info to student error")
                                                            self.messageLabel1.setText("Insertion Failed Try Again")
                                            else:
                                                    self.lineEdit_Email.setText("Invalid Email-ID")

                            except:
                                    self.lineEdit_Aadhar.setText("Invalid Aadhar No.")
            except:
                    self.lineEdit_Mobile.setText("Invalid Mobile No.")

            try:
                    if len(Seat10) != 7 or len(Seat12) != 7:
                            if len(Seat10) != 7:
                                self.lineEdit_10Seat.setText("Invalid Seat No")
                            else:
                                    self.lineEdit_12Seat.setText("Invalid Seat No")
                    else:
                            try:

                                    if int(Per10) >= 100 and int(Per12) >= 100 :
                                            self.lineEdit_10Seat.setText("Invalid Percentage")
                                            self.lineEdit_12Seat.setText("Invalid Percentage")
                                    elif int(Per10) >= 100:
                                            self.lineEdit_10Seat.setText("Invalid Percentage")
                                    elif int(Per12) >= 100:
                                            self.lineEdit_12Seat.setText("Invalid Percentage")
                                    else:

                                            try:
                                                    connection = sqlite3.connect("Project.db")
                                                    connection.execute(
                                                            "Insert into  Student_Verification(Username, Seat10, Board10, Yop10, Am10, Max10, Per10, Seat12, Board12, Yop12, Am12, Max12, Per12,Phy12,Math12,Chem12,Bifocal,Phycet,Mathcet,Chemcet,Totalcet)VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                                                            (self.user,Seat10, Board10, Yop10, Am10, Max10, Per10, Seat12, Board12, Yop12, Am12, Max12, Per12,Phy12,Math12,Chem12,Bifocal,Phycet,Mathcet,Chemcet,Totalcet))
                                                    self.messageLabel1.setText("Registration Successfull")
                                                    # self.Print_Preview.setEnabled(True)
                                                    connection.commit()
                                                    connection.close()
                                            except:
                                                    print("insertion error")
                                                    self.lineEdit_Fname.setText("Failed Try Again")
                            except Exception as a:
                                    print(a)
            except Exception as b:
                    if len(Seat10) != 7:
                            self.lineEdit_10Seat.setText("Invalid Seat No")
                    else:
                            self.lineEdit_12Seat.setText("Invalid Seat No")
                    print(b)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
